### ISSUE TITLE
jekyll vs pandoc for lesson template

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/lesson-template-ARCHIVED#4]
From https://github.com/datacarpentry/sql-ecology/pull/18#issuecomment-97504230

> They're similar to the SWC ones but use Jekyll rather than pandoc. The question though is if we should use the SWC template for consistency. There's good documentation now on how to use those templates, and it would make our lessons more interchangeable.
> 
> I worry that using pandoc reduced people's ability to be lesson developers, but I think the good documentation is helping, and once the lesson framework is up, people can contribute via github web or something like Authorea. Can we continue this discussion over on the lesson-template repo? I agree we need to come to a decision, and the sooner the better.

I like Jekyll here since it means that no one ever needs to build anything locally if they don't want to. They just need to push changes in the markdown. Of course if there are things that we can't live without that pandoc can support, then that may justify more complex tooling, and that's the decision that SWC made, but my preference is to try to make it work with just GitHub supported Jekyll.

**Comment by tracykteal** [comment]
We've decided to go ahead with using Jekyll for the templating, so local building isn't required.
