### ISSUE TITLE
Move here the Lesson Template wiki page from archived datacarpentry repo

### ISSUE THREAD

**Issue by hlapp** [datacarpentry/lesson-template-ARCHIVED#5]
The [Lesson template](https://github.com/datacarpentry/archive-datacarpentry/wiki/Lesson-template) wiki page on the [now-archived datacarpentry repo](https://github.com/datacarpentry/archive-datacarpentry/) was created by @fmichonneau during the hackathon in Finland. It should be moved to this repo.

See also datacarpentry/planning#1.

**Comment by lwasser** [comment]
agreed -- @tracykteal how do you want to handle this? should we simply copy it over? it's a good list of things we should consider / include.

**Comment by tracykteal** [comment]
Yes, let's move it over. I'll go do that. We can list @fmichonneau as the author.

**Comment by lwasser** [comment]
perfect. https://github.com/datacarpentry/lesson-template/wiki/Lesson-Template-Overview i started to create the page but wasn't sure how you like to handle changes to the repo :+1:

**Comment by fmichonneau** [comment]
Thanks @lwasser and @tracykteal ! :smile:
